{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "k1c-operator.namespace" . }}
  labels:
    {{- include "k1c-operator.labels" . | nindent 4 }}
{{- end }}
