{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: k1c-operator-metrics
  namespace: {{ include "k1c-operator.namespace" . }}
  labels:
    {{- include "k1c-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    {{- include "k1c-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
{{- end }}
