apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  annotations:
    cloudflare.com/compatibility-date: "2025-09-01"
spec:
  selector:
    matchLabels:
      app: hello
  template:
    spec:
      containers:
        - name: hello
          image: ./examples/hello-worker.mjs
          env:
            - name: REGION
              value: weur
          volumeMounts:
            - name: r2-media
              mountPath: /mnt/r2-media
            - name: kv-cache
              mountPath: /mnt/kv-cache
      volumes:
        - name: r2-media
          csi:
            driver: r2.k1c.io
            volumeAttributes:
              bucketRef: media
        - name: kv-cache
          csi:
            driver: kv.k1c.io
            volumeAttributes:
              namespaceRef: cache
