apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k1c-hello.workerRefName" . }}-config
data:
  GREETING: {{ .Values.config.greeting | quote }}
  REGION: {{ .Values.config.region | quote }}
